name: Nitronet
namespace: Nitronet
title: Nitronet Website
description: Nitronet is the web development lab of neiluJ
homepage: home
errorpage: error
directories: 
    pages: ./pages
    sources: ./php
    assets: ./bower_components
    forms: ./forms
    cache: ../cache
    config: ./config
domain:
    name: nitronet.org
    force: true
config: ~

page_config:
    active: true
    cache:
        public: true
        enable: false
        lifetime: 3600
    config: ~
    listeners: ~
    defaults: ~