name: Nitronet
namespace: Nitronet
title: Nitronet Website
description: Nitronet is the web development lab of neiluJ
homepage: home
errorpage: error
directories: 
    pages: ./pages
    sources: ./php
    assets: ./bower_components
    forms: ./forms
    cache: ../cache
    config: ./config
domain:
    name: nitronet.org
    force: true
config: ~
urls:
    "/blog/article/:slug$":
        page: blog/article
        parameters:
            slug:
                required: true
                regex: .*
    "/fwk/:package/api$":
        page: fwk/apidoc
        parameters:
            package:
                required: true
    "/fwk/:package/download$":
        page: fwk/download
        parameters:
            package:
                required: true
    "/fwk/:package/doc$":
        page: fwk/doc
        parameters:
            package:
                required: true
    "/fwk/:package/board$":
        page: fwk/board
        parameters:
            package:
                required: true
    "/fwk/:package$":
        page: fwk/intro
        parameters:
            package:
                required: true
    "/blog/:category":
        page: blog
        parameters:
            category:
                required: true
                regex: ".[a-zA-Z0-9\-_\s]+"
    "/:page$":
        parameters:
            page:
                required: false
                regex: .*
page_config:
    active: true
    cache:
        public: true
        enable: false
        lifetime: 3600
    config: ~
    listeners: ~
    defaults: ~
    datasources:
        packages: 
            class: Nitronet\FwkPackagesDataSource
            #service: serviceName
            constructor:
                - /home/neiluj/www/nitronet-www/site/fwk-packages.xml