name: Nitronet
namespace: Nitronet
title: Nitronet Website
description: Nitronet is the web development lab of neiluJ
homepage: home
errorpage: error
directories: 
    pages: ./pages
    sources: ./php
    assets: ./bower_components
    forms: ./forms
    cache: ../cache
    config: ./config
domain:
    name: nitronet.org
    force: true
config: ~
urls:
    "/blog/article/:slug":
        page: blog/article
        parameters:
            slug:
                required: true
                regex: .*
    "/fwk/:package/api$":
        page: fwk/apidoc
        parameters:
            package:
                required: true
                regex: "[a-zA-Z]+"
    "/fwk/:package$":
        page: fwk/intro
        parameters:
            package:
                required: true
                regex: "[a-zA-Z]+"
    "/blog/:category$":
        page: blog
        parameters:
            category:
                required: true
                regex: ".[a-zA-Z0-9\-_\s]+"
    "/:page":
        page: ~
        parameters:
            page:
                required: true
                regex: .*
                
page_config:
    active: true
    cache:
        public: true
        enable: false
        lifetime: 3600
    config: ~
    listeners: ~
    defaults: ~