template_ajax: fwk/apidoc-class-ajax
datasources:
        apidoc: 
            class: Nitronet\FwkApiDocDataSource
            #service: serviceName
            constructor:
                - /home/neiluj/www/framework/Core/build/apidoc/structure.xml